# Novata Data Analyst Role - Technical Take Home Task

Thank you for applying to Novata! We have prepared a small take home task. Please aim to spend about 3-5 hours on it. If a question is taking you a long time, please show where you've gotten up to, and move on to the next question.

The questions are designed to assess your technical abilities, inquisitiveness, and product mindset. We hope you enjoy them!

If you struggle to use colab, please feel free to share your results (showing your working) in a format that suits you.

Finally, please feel free to use Google, or equivalents. You will be asked to talk through your solutions in the next round, so make sure you have a good understanding of your answers.

Best of luck - we look forward to seeing what you come up with!

# I. SQL

Please answer these questions using SQL.

Recommended time: 30m

## Create Tables

We create and populate the tables `submetrics`, `answers`, and `structure`.

Submetrics are essentially questions, like "How many tons of CO2 did you emit this year?". `submetrics` details the standard library of questions a company can answer.

Answers are companies' answers to those questions. The relationship from submetrics to answers is one to many - many companies can have answers to the same submetric, over various years.

### Install Postgres and create the DB

In [ ]:
#The output of the installation is not displayed when %%capture is used at the start of the cell

!pip install SQLAlchemy==1.4.46
!pip install psycopg2

# Install postgresql server
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo service postgresql start
# Setup a password `postgres` for username `postgres`
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"
# Setup a database with name `sampledb` to be used
!sudo -u postgres psql -U postgres -c 'DROP DATABASE IF EXISTS novata_db;'
!sudo -u postgres psql -U postgres -c 'CREATE DATABASE novata_db;'

Requirement already satisfied: SQLAlchemy==1.4.46 in /usr/local/lib/python3.10/dist-packages (1.4.46)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy==1.4.46) (2.0.2)
Requirement already satisfied: psycopg2 in /usr/local/lib/python3.10/dist-packages (2.9.6)
 * Starting PostgreSQL 12 database server
   ...done.
ALTER ROLE
DROP DATABASE
CREATE DATABASE

In [ ]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [ ]:
# We will then connect to our Postgres DB
%sql postgresql://postgres:postgres@localhost:5432/novata_db

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])
Can't load plugin: sqlalchemy.dialects:postgresql
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

### Create the schema

In [ ]:
%%sql

CREATE SCHEMA IF NOT EXISTS sm;
set schema 'sm';

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

### Create tables

In [ ]:
%%sql
drop table if exists sm.submetrics;
drop table if exists sm.answers;

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [ ]:
%%sql

CREATE TABLE "submetrics" (
    id text PRIMARY KEY,
    name text NOT NULL,
    difficulty integer
)

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [ ]:
%%sql

CREATE TABLE "answers" (
    id numeric PRIMARY KEY,
    company_id numeric,
    submetric_id text,
    year integer,
    answer numeric
)

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [ ]:
%%sql

INSERT INTO answers (id, company_id, submetric_id, year, answer) VALUES
 (0.0, 1, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2017, 318.39129270190557),
  (1.0, 1, NULL, 2018, 1487.0543767930744),
  (2.0, 1, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2019, 1711.8796884706476),
  (3.0, 1, '91c2e9d5-3326-4374-9686-0402ca56df2f', NULL, 2785.351307513035),
  (4.0, 1, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2021, 3892.5242093535885),
  (5.0, 2, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2017, -790.3856582356723),
  (6.0, 2, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2018, NULL),
  (7.0, 2, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2019, 1283.4515852070788),
  (8.0, 2, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2020, 3873.6209227513204),
  (9.0, 2, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2021, NULL),
  (10.0, 3, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2017, -141.25391407658097),
  (11.0, 3, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2018, 2170.4852636587502),
  (12.0, 3, NULL, 2019, 2507.0190512765994),
  (13.0, 3, '91c2e9d5-3326-4374-9686-0402ca56df2f', NULL, 4573.261353448452),
  (14.0, 3, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2021, 4695.198600364415),
  (15.0, 4, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2017, NULL),
  (16.0, 4, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2018, 694.3972045414408),
  (17.0, 4, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2019, 2072.042523845678),
  (18.0, 4, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2020, 5207.103057262519),
  (19.0, 4, '91c2e9d5-3326-4374-9686-0402ca56df2f', 2021, 3051.958745662154),
  (20.0, 1, '3106d1e7-59bb-4509-a511-baeabea343e2', 2017, 512.0918414777085),
  (21.0, NULL, '3106d1e7-59bb-4509-a511-baeabea343e2', 2018, 737.4631095183762),
  (22.0, 1, '3106d1e7-59bb-4509-a511-baeabea343e2', 2019, 1348.8634438403017),
  (23.0, 1, '3106d1e7-59bb-4509-a511-baeabea343e2', 2020, NULL),
  (24.0, 1, '3106d1e7-59bb-4509-a511-baeabea343e2', 2021, 3810.2263203288912),
  (25.0, 2, '3106d1e7-59bb-4509-a511-baeabea343e2', 2017, -513.8435967161628),
  (26.0, 2, '3106d1e7-59bb-4509-a511-baeabea343e2', 2018, 127.14445397142238),
  (27.0, 2, '3106d1e7-59bb-4509-a511-baeabea343e2', 2019, 811.8737152244013),
  (28.0, 2, '3106d1e7-59bb-4509-a511-baeabea343e2', 2020, 6170.901278306805),
  (29.0, 2, '3106d1e7-59bb-4509-a511-baeabea343e2', 2021, 3015.134171180396),
  (30.0, NULL, '3106d1e7-59bb-4509-a511-baeabea343e2', 2017, -280.49160789478674),
  (31.0, 3, '3106d1e7-59bb-4509-a511-baeabea343e2', 2018, 212.30931318578718),
  (32.0, 3, '3106d1e7-59bb-4509-a511-baeabea343e2', 2019, 1525.2376637084099),
  (33.0, 3, '3106d1e7-59bb-4509-a511-baeabea343e2', 2020, 3109.9493688317484),
  (34.0, 3, '3106d1e7-59bb-4509-a511-baeabea343e2', 2021, 2417.6579111645215),
  (35.0, 4, '3106d1e7-59bb-4509-a511-baeabea343e2', 2017, -1012.4363679994995),
  (36.0, 4, '3106d1e7-59bb-4509-a511-baeabea343e2', 2018, 41.62389909485809),
  (37.0, 4, '3106d1e7-59bb-4509-a511-baeabea343e2', 2019, 1956.0710573606789),
  (38.0, 4, '3106d1e7-59bb-4509-a511-baeabea343e2', 2020, NULL),
  (39.0, 4, '3106d1e7-59bb-4509-a511-baeabea343e2', 2021, 4044.823321194416),
  (40.0, 1, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2017, -72.97900629502568),
  (41.0, 1, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2018, -140.9120115105602),
  (42.0, 1, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2019, 812.3516146891834),
  (43.0, 1, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2020, 3038.001894514847),
  (44.0, 1, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2021, 3308.91712230605),
  (45.0, 2, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2017, -638.7686539919135),
  (46.0, 2, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2018, 1558.46288902778),
  (47.0, 2, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', NULL, 1739.3711909769474),
  (48.0, 2, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2020, 2627.771537367214),
  (49.0, 2, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2021, 5115.972196225749),
  (50.0, 3, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2017, 1021.4662499322067),
  (51.0, 3, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2018, NULL),
  (52.0, 3, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2019, 2473.0533814836076),
  (53.0, 3, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2020, 2497.22438436684),
  (54.0, 3, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2021, 5947.856990282018),
  (55.0, NULL, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2017, 464.77201032423443),
  (56.0, 4, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2018, -198.005585446569),
  (57.0, 4, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2019, 1400.1221809071374),
  (58.0, 4, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2020, 2895.5088256912213),
  (59.0, 4, '5b3fb4a5-4146-47f5-b014-8789c6372e7e', 2021, 4416.478364556522),
  (60.0, 1, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2017, -577.5378234486665),
  (61.0, 1, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2018, 697.4429673889186),
  (62.0, 1, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2019, 1230.223289863451),
  (63.0, 1, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2020, NULL),
  (64.0, 1, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2021, NULL),
  (65.0, 2, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', NULL, NULL),
  (66.0, 2, NULL, 2018, -10.416665097090272),
  (67.0, 2, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2019, NULL),
  (68.0, 2, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2020, 2327.2090041124716),
  (69.0, NULL, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2021, 2124.641834320126),
  (70.0, 3, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2017, -538.5338519576212),
  (71.0, 3, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2018, 3121.0877220754624),
  (72.0, 3, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2019, 1378.8604041687265),
  (73.0, 3, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2020, 2623.2184890415106),
  (74.0, 3, NULL, 2021, 2469.597782358945),
  (75.0, 4, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2017, -369.686545292561),
  (76.0, 4, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2018, 1271.0719712304217),
  (77.0, 4, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2019, 2502.359552939538),
  (78.0, 4, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2020, 4399.598977245621),
  (79.0, 4, '27f724e2-35bc-4248-ada3-f3ae56dc7e88', 2021, 3484.0158199537186),
  (80.0, 1, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2017, 2950.6281551814386),
  (81.0, 1, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2018, 1447.8549093393897),
  (82.0, 1, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2019, 2453.7132560570867),
  (83.0, 1, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2020, 2897.4268305589153),
  (84.0, 1, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2021, 4277.898421423117),
  (85.0, 2, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2017, NULL),
  (86.0, 2, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2018, 608.0033369107902),
  (87.0, 2, NULL, 2019, 1628.386193912516),
  (88.0, 2, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2020, NULL),
  (89.0, 2, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2021, 2459.7838874973722),
  (90.0, 3, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2017, NULL),
  (91.0, 3, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2018, 55.758032099774255),
  (92.0, 3, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2019, 1907.0795204927063),
  (93.0, 3, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2020, NULL),
  (94.0, 3, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2021, 4663.095205398591),
  (95.0, 4, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2017, 1105.7204458316608),
  (96.0, 4, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2018, 1150.3361784897058),
  (97.0, 4, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2019, NULL),
  (98.0, 4, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2020, 3564.865595125676),
  (99.0, 4, 'bfde73d2-a9d7-4987-88b1-98f98b20a104', 2021, 4241.150185663917),
  (100.0, 1, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2017, -350.3883596654509),
  (101.0, 1, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2018, 2103.7306386651703),
  (102.0, 1, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2019, 1797.321047063448),
  (103.0, 1, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2020, 3863.3997013724925),
  (104.0, 1, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2021, 3370.499597237572),
  (105.0, 2, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2017, -248.29016141651246),
  (106.0, 2, 'd8cde421-9ccc-469a-8692-0a1f30146b50', NULL, 2773.8007645803473),
  (107.0, 2, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2019, 2465.6044154562837),
  (108.0, 2, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2020, 2681.071038489875),
  (109.0, 2, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2021, 4899.015147980596),
  (110.0, 3, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2017, -317.9370424556698),
  (111.0, NULL, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2018, -414.68376560924145),
  (112.0, 3, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2019, 1369.613294661602),
  (113.0, 3, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2020, 3910.5043002049297),
  (114.0, 3, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2021, 3785.025936715112),
  (115.0, 4, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2017, -300.9621093005054),
  (116.0, NULL, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2018, NULL),
  (117.0, 4, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2019, 1419.6177308226997),
  (118.0, 4, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2020, 3093.5088193724328),
  (119.0, 4, 'd8cde421-9ccc-469a-8692-0a1f30146b50', 2021, 5886.264156298189),
  (120.0, 1, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2017, -8.36665707722116),
  (121.0, 1, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2018, 2084.479299222723),
  (122.0, 1, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2019, 1622.4927300641823),
  (123.0, 1, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2020, 3395.612364242409),
  (124.0, 1, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2021, 2032.030860213502),
  (125.0, 2, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2017, 266.77866219699456),
  (126.0, 2, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2018, 1972.4368807126468),
  (127.0, 2, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2019, 2895.318750207829),
  (128.0, 2, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2020, 3249.2904500103186),
  (129.0, 2, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', NULL, 3698.669028030136),
  (130.0, 3, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2017, 400.5559530378583),
  (131.0, 3, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2018, 1339.9260431896885),
  (132.0, 3, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2019, 1345.0706481678383),
  (133.0, NULL, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2020, 3538.5717041531343),
  (134.0, 3, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2021, 3954.9441917877434),
  (135.0, 4, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2017, 136.40763667889854),
  (136.0, 4, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2018, 1710.1620554499277),
  (137.0, 4, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2019, NULL),
  (138.0, 4, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2020, 2188.527797450828),
  (139.0, 4, 'c3f942b5-76f2-4fce-97c3-375155ba93fe', 2021, 3639.5883638581854),
  (140.0, 1, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2017, -719.8826487295482),
  (141.0, 1, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2018, 1726.4193161389412),
  (142.0, 1, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2019, 1682.7323619913436),
  (143.0, 1, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2020, 2646.4704476492057),
  (144.0, NULL, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2021, 4907.808889044757),
  (145.0, 2, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2017, -653.8274351622787),
  (146.0, 2, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2018, 2104.0815652549804),
  (147.0, 2, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2019, 1982.092264709286),
  (148.0, 2, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2020, 2476.3309238142974),
  (149.0, 2, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2021, 4339.579180008976),
  (150.0, 3, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2017, -13.010942985147341),
  (151.0, 3, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2018, 2656.764211387711),
  (152.0, 3, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2019, 2322.2508963672076),
  (153.0, 3, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2020, 3259.5864002687103),
  (154.0, 3, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2021, 3557.384251342923),
  (155.0, 4, NULL, 2017, 241.5128273565673),
  (156.0, 4, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2018, 589.3670124944022),
  (157.0, 4, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2019, 1960.0317885354386),
  (158.0, 4, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', NULL, 3507.132906642492),
  (159.0, 4, 'a7dec739-9c84-4e79-b80e-f502d014c2f9', 2021, 5123.2121904275355)
    ;

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [ ]:
%%sql

INSERT INTO submetrics
VALUES
(E'91c2e9d5-3326-4374-9686-0402ca56df2f',E'Scope 1 Emissions',5),
(E'396b6fa5-5f88-46d3-9b42-9ca3a9694506',E'Scope 2 Emissions',5),
(E'3f259ac1-e194-4ea1-aee7-05369a470d9f',E'Scope 3 Emissions',10),
(E'3106d1e7-59bb-4509-a511-baeabea343e2',E'Net-zero target',2),
(E'721a7288-9fc3-4807-9f51-afc6a5e1ae15',E'Total GHG Emissions',5),
(E'5a3ad4da-aaca-465a-961d-40e7010a29ad',E'Does the company offer a retirement plan?',NULL),
(E'36a4c1a6-f767-4a9d-bc5c-b6f2544dfe51',E'Fossil fuel sector activity',2),
(E'b056704c-acc7-43f1-b96e-0487fd51b3bf',E'Total energy consumed, from all sources',8),
(E'9a4a39d4-07e3-405d-8da1-e3352a524ea5',E'Percentage of total energy consumed that is renewable energy',8),
(E'b8fdbd2c-e090-44c8-84ea-83c14195466d',E'Total fresh water withdrawn',8),
(E'6965631f-fa92-413e-9141-9c6e5b26ae88',E'Total fresh water withdrawn in regions with high or extremely high baseline water stress',10),
(E'b1d637cb-bdad-48b2-a98f-329a21187638',E'Total fresh water consumed, in Megaliters',8),
(E'106e2d06-2d97-4506-a26b-8770b68408d7',E'Total fresh water consumed in regions with high or extremely high baseline water stress\n',10),
(E'1bb00347-fabb-4f53-a088-0da2da8d8082',E'Emissions to water',10),
(E'bfdf9fb6-e3c7-45d4-baca-89d0ac0a118b',E'Tons of waste generated',10),
(E'1748593f-a4aa-4897-9e21-a1e92ef84393',E'Tons of hazardous waste generated',8),
(E'1faaaad5-b0c4-4adc-a837-9268a9922449',E'Percentage of waste generated that was hazardous',10),
(E'a3948cef-a06f-4ac3-a88f-5049a162516e',E'Biodiversity',8),
(E'5b3fb4a5-4146-47f5-b014-8789c6372e7e',E'Total number of board members',2),
(E'69a4cf2c-1ef2-4302-be7c-6adee437a01e',E'Number of women board members',2),
(E'9acb89bd-4c3d-45b4-9420-0f972f97f74f',E'Board member racial/ethnic group representation\n\n',8),
(E'6f12b5bc-dc68-4ef5-a01a-a6708f7d8d23',E'Number of board members from age group: under 30 years old',2),
(E'68f7b6f1-b168-4ce5-a8ec-8eba5bdf317b',E'What is the average FTE employee tenure?',NULL),
(E'cad58e1b-cd57-42df-b60b-26562c20571f',E'Number of board members from age group: 30-50 years old',2),
(E'de7ea55a-9bda-44ae-ad74-dd1f46e82273',E'Number of board members from age group: over 50 years old\n',2),
(E'95a46e40-9bce-4d83-bf5c-da3d055cbd8b',E'Number of board members with different national origin from country of headquarters\n',2),
(E'7cf8218f-3574-4309-a142-cba6e5ca997c',E'Number of LGBTQ board members\n',2),
(E'83b36394-f2f3-43d6-bc37-1048dc3f9317',E'Incidents of corruption',5),
(E'67689b93-6839-4640-b64d-14a0c739d1e2',E'Monetary losses as a result of legal proceedings associated with fraud, bribery or corruption, or other unethical business practices',8),
(E'519abf83-c26c-4ba9-8dbe-841e102408e1',E'What percentage of employees are paid an upper-middle or high income?',NULL),
(E'79909a9b-adce-4c02-bbd7-06cb023864b2',E'GRI disclosure',2),
(E'300ac663-9758-45f9-bbc5-ebe4dab32258',E'CDP disclosure',2),
(E'fe3c42b6-04c4-41d8-b44d-961361c903a3',E'CDSB disclosure',2),
(E'ebde12ce-2464-4bac-8e2a-f1d4716801cf',E'SASB disclosure',2),
(E'8783b323-fec5-4825-87b9-8318bafdacf0',E'TCFD disclosure',2),
(E'948efc6f-ac9a-419b-80d9-85c4bbeec386',E'Additional ESG reporting frameworks and standards',2),
(E'c5e21699-0bf1-4711-9e49-dbb64009004f',E'Does the company offer a profit participation incentive plan?',NULL),
(E'942c360d-849c-4888-b998-4885a3bd57c5',E'Violations of UNGC principles and OECD Guidelines for Multinational Enterprises',5),
(E'7c0043b3-229b-46d4-973a-0810322c99b9',E'Policies for UNGC principles and OECD Guidelines for Multinational Enterprises',5),
(E'107e3679-b9e6-486f-a35e-40250b80dcd5',E'Gender representation by job category',8),
(E'313159c6-05d3-4a30-9fe3-ee8fc0dc13a2',E'Gender and racial/ethnic group representation by job category',8),
(E'934867fa-183f-4fe1-af83-fed2c02072dd',E'Total cost of the workforce',5),
(E'028bd14b-ee54-443b-ad57-cda7e76eef86',E'Organic net new hires',2),
(E'27f724e2-35bc-4248-ada3-f3ae56dc7e88',E'Total net new hires',2),
(E'94704c8f-1985-42cc-bb4a-f2ef17c8164b',E'Annual Percent Attrition',2),
(E'fab370b5-1f75-45c5-ada3-55d85fa14575',E'Employee survey',2),
(E'0868eb60-6b4d-45c3-9904-d8ba6a7e8577',E'Percentage of employees responding to employee survey',2),
(E'269fbcba-cc36-45c3-8ffc-2115f4f1873a',E'Unadjusted gender pay gap',10),
(E'db0373dd-f5bb-4b93-aecd-884e2070615b',E'Unadjusted gender pay gap by job category',10),
(E'13b62460-b791-46f7-9269-77a5036bbacd',E'Racial pay gap',10),
(E'bd16b49b-b217-4924-91c2-a31d7dee577c',E'Racial pay gap by job category',10),
(E'cc5d0ee7-3e19-4114-9286-6d2d17cdfc05',E'Number of work-related injuries',5),
(E'83e85be6-b7f3-4905-9af5-4207005f1286',E'Number of work-related fatalities',2),
(E'fb5f4c58-900f-47c0-a6d9-13423817003e',E'Days lost due to injury',5),
(E'6dad067c-2c81-425d-a947-67ec08ebcf28',E'Number of data breaches',2),
(E'59adef1c-db79-43e8-955a-aa3c3e8e4b3a',E'Percentage of breaches involving personally identifiable information',2),
(E'ba1d939e-abb0-4af6-8143-e280719ccd30',E'Number of users/customers affected',2),
(E'd0c2da3e-516e-4c9d-b594-43fe517d5922',E'Controversial weapons',2),
(E'bfde73d2-a9d7-4987-88b1-98f98b20a104',E'Human Rights Policy',2),
(E'37778ed3-6d0e-4c37-83ad-751c89c8809c',E'Does the company offer a retirement plan?',NULL),
(E'd8cde421-9ccc-469a-8692-0a1f30146b50',E'Human Rights in Supplier Contracts',2),
(E'c3f942b5-76f2-4fce-97c3-375155ba93fe',E'Allegations of Human Rights Incidents',5),
(E'5d0be707-b2b0-4288-a178-7af1d063dd50',E'Emissions of inorganic pollutants',8),
(E'cd0b29b4-ec94-453c-9d06-b2cfe39c8dbf',E'Emissions of air pollutants',8),
(E'c3353bb7-0935-4e27-a725-934e0673426b',E'Emissions of ozone depletion substances',8),
(E'e9347838-726d-4fbf-af3f-22d90f30d355',E'Investments in companies without carbon emission reduction initiatives',8),
(E'd53d3e49-df6d-4e17-b8bc-c812a4dd04a4',E'Breakdown of energy consumption by type of non-renewable sources of energy',10),
(E'1283bf82-8f01-4c6e-b72b-a5d790749252',E'Water usage and recycling',10),
(E'1ecaeaf1-75f9-4824-a415-e18f2c14f54c',E'Company without water management policies',8),
(E'9cdf7e45-2e09-411e-94b2-98f76a0e186a',E'Exposure to areas of high water stress',8),
(E'fb55b151-37d6-4bb9-8166-2c9897a59326',E'Company producing chemicals',8),
(E'0d1532ac-29e7-48ec-8695-6a73baa6672b',E'Land degredation, desertification, soil sealing',10),
(E'1096e200-4454-4a21-b928-6c0e89497ab8',E'Company without sustainable land/agriculture practices',10),
(E'668672a7-32e6-4c54-8c4a-7b39ef419464',E'Company without sustainable oceans/seas practices ',10),
(E'7c44f059-8826-47e2-94b2-cca19d280baf',E'Non-recycled waste ratio',10),
(E'52e590e9-8bcc-4ec3-8dbf-e97ebe48cc53',E'Natural species and protected areas',10),
(E'aa5b0402-8a32-4499-9bf7-5930ccd90bec',E'Deforestation ',10),
(E'66b9be9f-f808-452b-aacf-f7181e62f1bd',E'Share of securities not certified as green ',5),
(E'c11cbed2-2111-48b0-b263-bf6981fe3c65',E'Rate of accidents',2),
(E'2f36ef35-dcc3-48c6-953d-e638802f13ab',E'Lack of a supplier code of conduct',2),
(E'68b263f6-145d-409c-8cf6-679db9ef567f',E'Lack of grievance/ complaints handling mechanism related to employee matters',5),
(E'4332355f-c2d1-4625-84a1-0955d7ff2bd8',E'Insufficient whistleblower protection',2),
(E'f23c176a-4445-4296-977b-83c0d479363b',E'Incidents of discrimination',5),
(E'eaaa46d0-bc3a-4cb0-91d9-c4d04fc7a07e',E'Incidents of discrimination leading to sanctions',2),
(E'd9fda682-bd1a-447d-a917-6365af7cf9d1',E'Excessive CEO pay ratio',5),
(E'a7dec739-9c84-4e79-b80e-f502d014c2f9',E'Lack of due diligence',2),
(E'cc165d31-d2c0-46d7-a9d5-d5f0f4fe2eab',E'Lack of processes and measures for preventing trafficking in human beings',2),
(E'939f6886-2c2e-4db6-8a7b-4e4b01ce6826',E'Operations and suppliers at signficiant risk of incidents of child labour',2),
(E'a8a04abe-66d7-43db-ad57-83b75009f94d',E'Operations and suppliers at significant risk of incidents of forced or compulsory labour',2),
(E'79d4ff40-1184-4a18-a2d3-61a24456b8e0',E'Number of indentified cases of severe human rights issues and incidents',5),
(E'77b72af4-592d-4f64-bb00-95a70dcdd961',E'Lack of anti-corruption and anti-bribery policies',5),
(E'48e5dbcf-55ef-41d6-a628-6c8878f028fa',E'Cases of insufficient action taken to address breaches of standards of anti-corruption and anti-bribery',5),
(E'a3f3686c-0404-4fb0-8975-40612f055929',E'Number of convictions for violation of anti-corruption and anti-bribery laws',5),
(E'4d6e811f-ec4b-4f33-9ce4-a60287a905d9',E'Amount of fines for violation of anti-corruption and anti-bribery laws',5),
(E'680f0ca2-e837-4333-b12c-09181a0952d4',E'Equal opportunity and non-discrimination policy',2),
(E'55ea3c5c-477a-43a6-af2e-f37c07544c79',E'Anti-harassment policy',2),
(E'39e54307-92ed-4dda-b23d-691fb0a72e61',E'Investments in companies without workplace accident prevention policies',2),
(E'28d62364-66b4-43b5-843d-1eb09944d153',E'Whistleblower policy',2),
(E'ce20f1b0-6e98-4942-a073-2d04c2e14f17',E'Data privacy policy',2),
(E'13499eed-a9f9-467e-95ee-8fb9cb0eff37',E'Health and safety policy',2),
(E'cc5e4188-b523-4cfc-a917-8991a4b5cc8e',E'ILPA Diversity in Action signatory',2),
(E'7e119d93-8213-499b-b7b8-9d5a3f800070',E'Diversity metrics for the Firm/Management Company',2),
(E'1dcb531c-f981-4ed8-8577-56a228a83484',E'Diversity metrics at portfolio company level',2),
(E'a0719b22-05b9-42ec-8984-1bd6b9ef80d2',E'DEI policy requirement for portfolio companies',2),
(E'13d81f5f-4d1f-4682-98c0-34e9fadd3b5e',E'Code of Conduct/Code of Ethics requirement for portfolio companies',2),
(E'6680be4c-729b-42c9-a8e7-b2c0fec3baec',E'Equitable Pay Policy requirement for portfolio companies',2),
(E'44c54595-bb9a-4635-9930-b299e5bbcfb0',E'Family Leave Policy requirement for portfolio companies',2),
(E'48e085f7-095e-48fc-a041-c20332e89483',E'Portfolio company policy requirement for Recruiting Diverse Staff/Underrepresented Groups',2),
(E'd678c539-dfab-4a58-983a-e0e0ad5145e2',E'Employee Engagement Survey requirement for portfolio company',2),
(E'765fe17d-a742-4c33-978e-40b967eded4f',E'Portfolio company requirement for inclusive Employee Engagement Programs',2),
(E'f580d118-cd68-4c30-bb94-e3cff4a5a026',E'Performance Appraisal Policy requirement for portfolio companies',2),
(E'83c20ebf-6b92-4420-8a80-45dfb45162ec',E'Portfolio company procedural requirements for Harassment and Discrimination Reporting',2),
(E'f1881e21-126b-4808-9ea5-433ae572fbc2',E'Supplier Diversity Program requirement for portfolio companies',2),
(E'f99f6179-ab67-45f9-b6ba-1f468b3df75e',E'Assessment of Firm-wide culture',5),
(E'530e9f0b-4fac-4b30-b297-2408b1d80b74',E'Anticipated changes to Firm’s policies',5),
(E'fe368465-710d-45a5-b9a1-07c8513e2b12',E'Description of Firm\'s Family Leave policy',5),
(E'93f0ec06-6645-41d3-8d7e-d7c10d0443d0',E'Description of Firm’s recruiting policies for Diverse Staff/Underrepresented Groups',5),
(E'08ca647b-b9d9-471b-aefd-fbeabc64e3f8',E'Description of processes for identifying and addressing hiring biases',5),
(E'960bbd57-4e09-475e-acdc-dab4023672c2',E'Firm\'s partnership with organizations attracting/promoting underrepresented groups',5),
(E'c7d46fe5-580d-44e3-9329-6eaf9f12dc40',E'Employee Engagement programs at the Firm level for Diverse Staff/Underrepresented Groups',5),
(E'e2e588af-f011-4035-98cb-3d5e3c07a9ef',E'Disclosure of formal charges against Firm employees relating to harassment, misconduct, or discrimination',2),
(E'35e99772-80a8-4fd4-b6bd-81515d4845ca',E'DEI policies at the Firm level',5),
(E'a2357459-3131-4b21-8098-6ca756603e63',E'Performance appraisal process and DEI contributions within the Firm',5),
(E'fbc65880-0708-4532-ba4f-7f5f349339fd',E'Equitable Pay policies for both Firm and portfolio company employees',5),
(E'3395a9b7-66a5-430d-b60c-0bf55d6a38b4',E'DEI training given to both Firm and portfolio company employees',5),
(E'23bc150d-49fe-44cf-8446-1b81ca768841',E'Firm’s DEI goal setting and oversight',5),
(E'd8f88afb-0d05-4720-96e6-634570ce0454',E'Does the company offer a profit participation incentive plan?',NULL),
(E'ffd18abb-67cd-4164-bd10-fad44a12ad2d',E'Firm’s consideration of DEI in overall investment strategy',5),
(E'2cfcb758-c262-4509-aeb8-bce3182b8d71',E'Processes related to Firm’s evaluation of supplier and vendor diversity',5),
(E'39c614c8-f110-40d0-aacf-e9f6d75b5ecd',E'Formal commitment made by the Firm to enhance Board diversity at portfolio company level',5),
(E'4ddf103d-5696-47d4-955f-8467e461252d',E'Contributions by the Firm to improve DEI in private markets',5),
(E'aebce134-c0cb-4b88-a531-061db8b001cd',E'What is the average FTE employee tenure?',NULL),
(E'80fb70ff-8707-4c8f-8634-885e9d6f5411',E'What percentage of employees are paid an upper-middle or high income?',NULL),
(E'8a878ff3-ca3d-429e-8720-33b6ab636a99',E'Does the company offer a profit participation incentive plan?',NULL),
(E'79d451d6-e2b7-4034-9fea-74aa0ba291ce',E'Does the company offer a retirement plan?',NULL),
(E'03ded772-12e8-46d8-b0e1-4ffa949f42a5',E'What is the average FTE employee tenure?',NULL),
(E'84686851-61e4-4da7-937e-0f5d54b2da73',E'What percentage of employees are paid an upper-middle or high income?',NULL);

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

## 1. What is the % split of difficulties in the table `submetrics`?

Please show your working!

In [ ]:
%%sql

SELECT * FROM submetrics LIMIT 1

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

## 2. For every submetric where the name contains the word "Total" (case insensitive), what are the mean and median yearly answers?

In [ ]:
%%sql

SELECT * FROM submetrics LIMIT 1;

 * postgresql://postgres:***@localhost:5432/novata_db
1 rows affected.

[('91c2e9d5-3326-4374-9686-0402ca56df2f', 'Scope 1 Emissions', 5)]

# II. Python: Data Analysis
We now read in two new tables to Pandas. Using only these tables, please answer the questions below in Python, or another language of your choosing.

Recommended time: 120-240m

## Read in Data

In [ ]:
import gdown
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Read in companies data
url='https://drive.google.com/uc?id=1MDrl146kpuVEYTeebAfLyvhwFXieg-ot'
output='companies.csv'
gdown.download(url, output, quiet=False)

companies_df = pd.read_csv('companies.csv', index_col=0,
                           na_values=['', 'nan'],
                           keep_default_na=False)

# Read in answers data
url='https://drive.google.com/uc?id=1MEom5o0L9GD9OE4-_-3YshV4WxIRHcwU'
output='answers.csv'
gdown.download(url, output, quiet=False)

answers_df = pd.read_csv('answers.csv', index_col=0)

Downloading...
From: https://drive.google.com/uc?id=1MDrl146kpuVEYTeebAfLyvhwFXieg-ot
To: /content/companies.csv
100%|██████████| 46.8k/46.8k [00:00<00:00, 21.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1MEom5o0L9GD9OE4-_-3YshV4WxIRHcwU
To: /content/answers.csv
100%|██████████| 767k/767k [00:00<00:00, 98.3MB/s]

## 1. Data Cleaning and Preprocessing
* Identify and handle missing values appropriately.
* Check for duplicates and remove them if necessary.
* Convert data types if needed.

In [ ]:
companies_df.head(1)

    id        name location  total_employees  annual_revenue_usd
0  0.0  pDkOTmAbAm       AF              NaN                 NaN

In [ ]:
answers_df.head(1)

   id  metric_id             metric  company_id   unit       value    year
1 NaN        1.0  Scope 1 Emissions         0.0  tCO2e  410.168732  2019.0

## 2. Warming up

#### 1. What proportion of companies are based in Europe?

In [ ]:
companies_df.head(1)

    id        name location  total_employees  annual_revenue_usd
0  0.0  pDkOTmAbAm       AF              NaN                 NaN

#### 2. What is the mean number of total employees for all non-European companies?

In [ ]:
companies_df.head(1)

    id        name location  total_employees  annual_revenue_usd
0  0.0  pDkOTmAbAm       AF              NaN                 NaN

## 3. Data Visualisation and Exploratory Data Analysis

Visualise the data using a package of your choice. Tell us a story with the data.

Deliverables:

* A Jupyter notebook or any other preferred programming environment containing your analysis code. This can just be in the cells below, in this notebook.
* A report summarizing your findings, insights, and recommendations based on the analysis.
* Any visualizations or charts that support your analysis.

This could take you days, of course - please limit yourself for your own sake :) We're much more interested in seeing your style of thinking and analysis than a polished, complete product.

In [ ]:
companies_df.head(1)

    id        name location  total_employees  annual_revenue_usd
0  0.0  pDkOTmAbAm       AF              NaN                 NaN

In [ ]:
answers_df.head(1)

   id  metric_id             metric  company_id   unit       value    year
1 NaN        1.0  Scope 1 Emissions         0.0  tCO2e  410.168732  2019.0

## 4. [Optional] Data Science

*If you do not have a data science background and are not looking to expand into data science in the near term, please ignore this question.*

Build a predictive model to estimate a company's annual revenue, using any set of non-revenue variables as inputs.

Please only use the two tables read into this section. We're more interested in general strategy than you creating a valuable model, so feel free to gesture to things like hyper-param tuning rather than spending a long time fiddling with them.

In [ ]:
companies_df.head(1)

    id        name location  total_employees  annual_revenue_usd
0  0.0  pDkOTmAbAm       AF              NaN                 NaN

In [ ]:
answers_df.head(1)

   id  metric_id             metric  company_id   unit       value    year
1 NaN        1.0  Scope 1 Emissions         0.0  tCO2e  410.168732  2019.0

# III. Product Metrics

Choose an online product that you know well, and focus on a particular feature they offer. For example, google offers users a search engine, and amazon presents users recommended items. Feel free to use one of the above examples if you like!

Post an image of, and briefly describe, the product and feature you've chosen.

Suppose you were the data specialist assisting a team launching this feature. How would you measure the success, or otherwise, of this feature? What metrics would you recommend they track, and why?

Recommended time: 30-60m

# IV. [Optional] Mathematics and Modelling

Question: You have a wire cube with edges of unit length. The game: an ant
starts on one vertex and every turn moves randomly to one of the three vertices connected to its current vertex, each with equal probability. Stop the game when the ant reaches the vertex directly opposite its starting point (so at a minimum 3 moves away). What is the [expected length](https://en.wikipedia.org/wiki/Expected_value) of the path taken to reach this vertex? Generalise to d dimensions.

Create a function that outputs the answer on an input of d dimensions, for int ` 1 <= d <= 100000000`. Feel free to solve this via any method you like, analytic or otherwise - though note, there is an analytic solution.

Recommended time: As long as it's interesting for you :)

In [ ]:
def ant(d: int) -> float:
  pass